# Generated by Django 4.1 on 2022-11-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_title', models.CharField(max_length=10)),
                ('Post_Content', models.CharField(max_length=100)),
                ('Post_Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
