# Generated by Django 4.1 on 2022-11-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_details',
            name='Post_comment',
            field=models.TextField(default='post comment'),
        ),
        migrations.AddField(
            model_name='post_details',
            name='Post_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post_details',
            name='Post_Image',
            field=models.ImageField(default='D:/sem7/ADF/LAB/NU_SocialMedia/826405.fig.0010a.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post_details',
            name='Post_title',
            field=models.CharField(max_length=50),
        ),
    ]
