# Generated by Django 4.1 on 2022-11-18 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_post_details_post_comment_post_details_post_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_details',
            name='Post_owner',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='post_details',
            name='Post_comment',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=200)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.post_details')),
            ],
        ),
    ]
