# Generated by Django 4.1 on 2022-11-19 12:48

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_post_details_post_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_details',
            name='Post_owner',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=50),
        ),
    ]
