# Generated by Django 4.1 on 2022-11-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_alter_post_details_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_owner',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='post_details',
            name='Post_owner',
            field=models.CharField(default='', max_length=50),
        ),
    ]
