# Generated by Django 4.1.2 on 2022-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Register", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=10)),
                ("password", models.CharField(default="1234", max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[("1", "Male"), ("2", "Female"), ("3", "Other")],
                        default="1",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Contact",),
    ]
